"""Abstract Fleet client interface.

Both mock and real implementations conform to this Protocol, so tools
don't need to care which one they're talking to.
"""
from __future__ import annotations

from typing import Protocol


class FleetClient(Protocol):
    # --- Read ---
    def get_status(self) -> dict: ...
    def get_location(self) -> dict: ...
    def get_charge_info(self) -> dict: ...

    # --- Climate ---
    def set_climate(self, on: bool, temp_c: float | None = None) -> dict: ...

    # --- Lock ---
    def lock(self) -> dict: ...
    def unlock(self) -> dict: ...

    # --- Charging ---
    def start_charging(self) -> dict: ...
    def stop_charging(self) -> dict: ...

    # --- Signals ---
    def flash_lights(self) -> dict: ...
    def honk_horn(self) -> dict: ...
