"""Tesla Vehicle Command Protocol (TVCP) signing wrapper.

Control commands on 2021+ Tesla vehicles require ECDSA-signed payloads using
a Virtual Key paired with the car. We don't reimplement TVCP in Python —
instead we shell out to Tesla's official Go CLI `tesla-control`, which:
    1. Reads our private key (PEM)
    2. Reads an OAuth access token
    3. Builds + signs the command locally
    4. POSTs to Tesla Fleet API's /command/ endpoint
    5. Parses and returns the result

We wrap it with:
    - Automatic token injection via -token-file (temp file, 0600 perms, deleted)
    - Error classification (asleep / unauthorized / unpaired / generic)
    - Helpful error messages bubbled up to the agent

Prerequisites on the host:
    - tesla-control binary (built from github.com/teslamotors/vehicle-command)
    - Virtual Key private PEM (generated by scripts/generate_virtual_key.py)
    - Virtual Key paired with the vehicle via Tesla mobile app
"""
from __future__ import annotations

import logging
import os
import subprocess
import tempfile
import time
from dataclasses import dataclass
from pathlib import Path

from tesla_skill.auth import oauth
from tesla_skill.config import settings

log = logging.getLogger(__name__)

# Substrings we look for in tesla-control stderr to classify the failure.
_ASLEEP_MARKERS = ("asleep", "vehicle unavailable", "408", "request timeout")
_UNAUTHORIZED_MARKERS = ("unauthorized", "401", "403", "invalid token")
_UNPAIRED_MARKERS = ("not paired", "key not found", "no valid key", "virtual key")


@dataclass
class SignerResult:
    ok: bool
    stdout: str = ""
    stderr: str = ""
    error_type: str | None = None  # "asleep" | "unauthorized" | "unpaired" | "missing_binary" | "missing_key" | "timeout" | "other"

    @property
    def friendly_reason(self) -> str:
        return {
            "asleep": "Vehicle is in deep sleep and could not be woken",
            "unauthorized": "OAuth token invalid or scope insufficient — re-authorize",
            "unpaired": "Virtual Key not paired with the vehicle yet",
            "missing_binary": "tesla-control executable not found (set TESLA_CONTROL_BINARY)",
            "missing_key": "Virtual Key private PEM not found (set TESLA_PRIVATE_KEY_PATH)",
            "timeout": "Command timed out (network or vehicle unresponsive)",
            "other": self.stderr.strip() or "Unknown error",
        }.get(self.error_type or "other", self.stderr.strip() or "Unknown error")


class TeslaControl:
    """Thin wrapper around the `tesla-control` Go binary."""

    def __init__(self, vin: str) -> None:
        self.vin = vin
        self.binary = Path(settings.tesla_control_binary)
        self.key_path = Path(settings.tesla_private_key_path)

    # ---------- internals ----------
    def _preflight(self) -> SignerResult | None:
        if not self.binary.exists():
            return SignerResult(False, error_type="missing_binary")
        if not self.key_path.exists():
            return SignerResult(False, error_type="missing_key")
        return None

    def _classify(self, stderr: str) -> str:
        s = stderr.lower()
        for m in _UNPAIRED_MARKERS:
            if m in s:
                return "unpaired"
        for m in _UNAUTHORIZED_MARKERS:
            if m in s:
                return "unauthorized"
        for m in _ASLEEP_MARKERS:
            if m in s:
                return "asleep"
        return "other"

    # ---------- core execution ----------
    def run(self, command: str, *args: str, timeout: int = 30) -> SignerResult:
        """Execute one tesla-control command. Token injected via temp file."""
        pre = self._preflight()
        if pre is not None:
            return pre

        token = oauth.get_valid_access_token()

        # Write token to a 0600 temp file — tesla-control reads first line.
        tf = tempfile.NamedTemporaryFile(
            mode="w", delete=False, dir="/tmp", prefix="ts-", suffix=".token"
        )
        try:
            os.chmod(tf.name, 0o600)
            tf.write(token)
            tf.flush()
            tf.close()

            cmd = [
                str(self.binary),
                "-key-file", str(self.key_path),
                "-vin", self.vin,
                "-token-file", tf.name,
                command,
                *args,
            ]

            log.info("tesla-control: %s %s", command, " ".join(args))
            try:
                r = subprocess.run(
                    cmd,
                    capture_output=True,
                    text=True,
                    timeout=timeout,
                    env={**os.environ, "PATH": "/usr/local/bin:/usr/bin:/bin"},
                )
            except subprocess.TimeoutExpired:
                return SignerResult(False, error_type="timeout")

            if r.returncode == 0:
                return SignerResult(True, r.stdout, r.stderr)

            error_type = self._classify(r.stderr)
            log.warning(
                "tesla-control failed (rc=%s, type=%s): %s",
                r.returncode, error_type, r.stderr.strip()[:300]
            )
            return SignerResult(False, r.stdout, r.stderr, error_type)
        finally:
            try:
                os.unlink(tf.name)
            except FileNotFoundError:
                pass

    # ---------- wake flow ----------
    def wake_and_retry(
        self, command: str, *args: str, wake_timeout: int = 30, cmd_timeout: int = 30
    ) -> SignerResult:
        """Run command; if the car is asleep, wake it and retry once."""
        first = self.run(command, *args, timeout=cmd_timeout)
        if first.ok or first.error_type != "asleep":
            return first

        log.info("car is asleep, attempting wake")
        wake = self.run("wake", timeout=wake_timeout)
        if not wake.ok:
            log.warning("wake failed: %s", wake.stderr.strip()[:200])
            time.sleep(2)

        return self.run(command, *args, timeout=cmd_timeout)
